trigger:
- main  # Déclenche le pipeline sur des commits dans la branche main

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrurl: 'lavender.azurecr.io'  # URL du registre ACR
  kubernetesServiceConnection: 'K8S_SERVICE_CONNECTION'  # Service Connection pour Kubernetes
  namespace: 'default'  # Namespace Kubernetes
  releaseName: 'sampleapi-release'  # Nom du release Helm

stages:
# **Stage 1 - Build et Push Docker Image**
- stage: Build
  displayName: "Build and Push Docker Image"
  jobs:
    - job: BuildAndPush
      displayName: "Build and Push Docker Image"
      steps:
        # Connexion à Azure pour s'authentifier auprès de l'ACR
        - task: AzureCLI@2
          displayName: "Login to Azure ACR"
          inputs:
            azureSubscription: $(kubernetesServiceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              echo "Logging in to ACR..."
              az acr login --name $(acrurl)

        # Construction de l'image Docker
        - script: |
            echo "Building Docker image..."
            docker build -t $(acrurl)/sampleapi:$(Build.BuildId) .
          displayName: "Build Docker Image"

        # Pousser l'image Docker dans l'ACR
        - script: |
            echo "Pushing Docker image to ACR..."
            docker push $(acrurl)/sampleapi:$(Build.BuildId)
          displayName: "Push Docker Image to ACR"

# **Stage 2 - Package Helm Chart**
- stage: PackageHelm
  displayName: "Package Helm Chart"
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: HelmPackage
      displayName: "Package Helm Chart"
      steps:
        - task: HelmInstaller@1
          displayName: 'Install Helm'

        - script: |
            helm package ./helm --destination $(System.ArtifactsDirectory)/helm --version $(Build.BuildId)
          displayName: "Package Helm Chart"

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Helm Chart as Artifact'
          inputs:
            targetPath: '$(System.ArtifactsDirectory)/helm'
            artifact: 'helm-chart'

# **Stage 3 - Déploiement Manuel**
- stage: Deploy
  displayName: "Deploy to AKS (Manual)"
  dependsOn: PackageHelm
  condition: succeeded()
  jobs:
    - deployment: DeployApp
      displayName: "Manual Approval & Deploy to AKS"
      environment: "aks-environment"  # L'environnement configuré dans Azure DevOps
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                displayName: 'Download Helm Chart Artifact'
                inputs:
                  artifact: 'helm-chart'
                  path: '$(System.ArtifactsDirectory)/helm'

              - task: HelmDeploy@0
                displayName: 'Deploy to Kubernetes'
                inputs:
                  azureSubscription: $(kubernetesServiceConnection)
                  azureResourceGroup: 'K8S_RG'
                  kubernetesCluster: 'MyAKSCluster'
                  namespace: $(namespace)
                  command: upgrade
                  chartType: FilePath
                  chartPath: '$(System.ArtifactsDirectory)/helm/sampleapi-$(Build.BuildId).tgz'
                  releaseName: $(releaseName)
                  overrideValues: |
                    image.repository=$(acrurl)/sampleapi
                    image.tag=$(Build.BuildId)
                  install: true
