variables:
  acrName: 'lavender'
  acrurl: 'lavender.azurecr.io'
  dockerRegistryServiceConnection: 'ACR-Docker-Connection'  # Connexion Docker/ACR
  kubernetesServiceConnection: 'K8S_SERVICE_CONNECTION'     # Connexion Kubernetes
  namespace: 'default'
  releaseName: 'sampleapi-release'

stages:
- stage: Build
  displayName: "Build and Push Docker Image"
  jobs:
    - job: BuildAndPush
      displayName: "Build and Push Docker Image"
      steps:
        - task: Docker@2
          displayName: "Build and Push Docker Image"
          inputs:
            containerRegistry: 'ACR-Docker-Connection'  # Connexion correcte à ACR
            repository: 'sampleapi'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: '$(Build.BuildId)'

- stage: PackageHelm
  displayName: "Package Helm Chart"
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: HelmPackage
      displayName: "Package Helm Chart"
      steps:
        - task: HelmInstaller@1
          displayName: 'Install Helm'

        - script: |
            echo "Checking Helm Chart structure..."
            if [ ! -f ./helm/Chart.yaml ]; then echo "Chart.yaml not found!"; exit 1; fi
            helm package ./helm --destination $(System.ArtifactsDirectory)/helm --version $(Build.BuildId)
          displayName: "Package Helm Chart"

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Helm Chart as Artifact'
          inputs:
            targetPath: '$(System.ArtifactsDirectory)/helm'
            artifact: 'helm-chart'

- stage: Deploy
  displayName: "Deploy to AKS (Manual)"
  dependsOn: PackageHelm
  condition: succeeded()
  jobs:
    - deployment: DeployApp
      displayName: "Manual Approval & Deploy to AKS"
      environment: "aks-environment"
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2
                displayName: 'Download Helm Chart Artifact'
                inputs:
                  artifact: 'helm-chart'
                  path: '$(System.ArtifactsDirectory)/helm'

              - task: HelmDeploy@0
                displayName: 'Deploy to Kubernetes'
                inputs:
                  azureSubscription: 'K8S_SERVICE_CONNECTION'  # Connexion Kubernetes
                  azureResourceGroup: 'K8S_RG'
                  kubernetesCluster: 'MyAKSCluster'
                  namespace: $(namespace)
                  command: upgrade
                  chartType: FilePath
                  chartPath: '$(System.ArtifactsDirectory)/helm/sampleapi-$(Build.BuildId).tgz'
                  releaseName: $(releaseName)
                  overrideValues: |
                    image.repository=$(acrurl)/sampleapi
                    image.tag=$(Build.BuildId)
                  install: true