# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  author: Zineb Zahir
  name: sampleapi
  type: api

# Déploiement
replicaCount: 1

# Configuration de l'image Docker
image:
  repository: lavender.azurecr.io/sampleapi
  pullPolicy: IfNotPresent
  tag: "91"   # Modifiez dynamiquement via Azure DevOps

# Secret pour l'accès au registre
imagePullSecrets:
  - name: lavender-acr-secret

# Conteneur principal
containers:
  - name: nodesampleapi
    image: lavender.azurecr.io/sampleapi:91
    ports:
      - containerPort: 80

# Nom personnalisé (optionnel)
nameOverride: ""
fullnameOverride: ""

# Compte de service Kubernetes
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Annotations pour les Pods
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "80"

# Contexte de sécurité des Pods
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 2000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

# Service Kubernetes
service:
  type: LoadBalancer   # Expose le service au monde extérieur
  port: 80

# Ingress (optionnel)
ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: sampleapi.lavender.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sampleapi-tls
      hosts:
        - sampleapi.lavender.com

# Gestion des ressources
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

# Gestion des nœuds Kubernetes
nodeSelector: {}
tolerations: []
affinity: {}

# Variables d'environnement (optionnel)
env:
  - name: APP_ENV
    value: "production"
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: db-secret
        key: db-host